### ISSUE TITLE
FluxV1: Helm deployments via private git repo do not deploy

### ISSUE THREAD

**Issue by marekzan** [cloudogu/gitops-playground#39]
After switching to private repositories the helm-operator of fluxv1 is not able to sync the chart from the git repository if it is private.
It is necessary to implement a mechanism so that the helm operator can read private chart repositories.

Possible solution: https://github.com/fluxcd/helm-operator/blob/master/chart/helm-operator/README.md#use-a-private-git-server

**Comment by schnatterer** [comment]
Flux V1 has been removed in the meantime as it is no longer maintained
