### ISSUE TITLE
Jenkins CASC: Pin plugin dependencies

### ISSUE THREAD

**Issue by phaenr** [cloudogu/gitops-playground#71]
# Current

We have plugins that need to be installed pinned in `plugins.txt`. Those plugins may have plugin dependency to ones we do not pin. When downloading and installing our pinned plugins, the resolved plugins get installed in the `latest` version.

# Issue

Updates to those transitive dependencies may lead to a broken jenkins, as an updated plugin may e.g. require a higher jenkins version. In this case, the commit that ran previously ran and built successful wont work anymore. This does in fact break our playground without any one touching it.

# Possible solution

We could determine all the plugins we got plus their transitive dependencies and pin them all into the `plugins.txt`. This ensures build stability and really reproducible builds of the infrastructure.

**Comment by schnatterer** [comment]
Fixed in #78
